version: 2
jobs:
  build:
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run: npm install --no-optional
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}-{{ .BuildNum }}
          paths:
            - node_modules
      - run: npm test
      - store_artifacts:
          path: coverage
notify:
  webhooks:
    - url: https://bot.ambassify.com/publish/circleci/master
